name = "Digital Garden"
license = "MIT"
licenselink = "https://github.com/apvarun/digital-garden-hugo-theme/blob/master/LICENSE"
description = "Build your own personal Digital Garden effortlessly with this Hugo theme"
homepage = "https://github.com/apvarun/digital-garden-hugo-theme"
demosite = "https://digital-garden-hugo-theme.vercel.app/"
tags = ["Hugo", "theme", "digital garden", "blog", "modern", "responsive"]
features = ["clean", "3 column", "minimal", "digital garden", "mobile", "personal", "responsive", "simple", "tailwind", "blog", "white"]
min_version = "0.121.1"

baseURL = "http://frizzande.io/"
languageCode = "en-au"
title = "frizzande"

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "flowers and sunshine"
#  images = ['/digital-garden-logo.png']
  enableSearch = true

[Params.newsletter]
  provider = "buttondown"
  path = "frizzande"
  title = ""
  description = "thoughts in words"

[menu]
[[menu.main]]
  name = 'home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'about'
  url = '/about'
  weight = 2
[[menu.main]]
  name = 'words'
  url = '/words'
  weight = 3
#[[menu.main]]
#  name = 'audio'
#  url = '/audio'
#  weight = 4
#[[menu.main]]
#  name = 'images'
#  url = '/images'
#  weight = 5

# [[menu.social]]
#   name = 'Twitter'
#   url = 'https://twitter.com'
#   weight = 1
# [[menu.social]]
#   name = 'GitHub'
#   url = 'https://github.com'
#   weight = 2
# [[menu.social]]
#   name = 'LinkedIn'
#   url = 'https://linkedin.com'
#   weight = 3
[[menu.social]]
  name = 'Instagram'
  url = 'https://instagram.com/frizzande'
  weight = 4
#[[menu.social]]
#  name = 'Dribbble'
#  url = 'https://dribbble.com'
#  weight = 5
#[[menu.social]]
#  name = 'Codepen'
#  url = 'https://codepen.io'
#  weight = 6
#[[menu.social]]
#  name = 'Twitch'
#  url = 'https://twitch.com'
#  weight = 7
[[menu.social]]
  name = 'Email'
  url = 'mailto:frizzande@gmail.com'
  weight = 8
#[[menu.social]]
#  name = 'RSS'
#  url = '/articles/index.xml'
#  weight = 9


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true


[author]
  name = "Varun A P"
  homepage = "https://apvarun.com"

